{% set name = "yapf" %}
{% set version = "0.16.3" %}
{% set sha256 = "3246776a1cbb43a91ea96a6fa6e21e0c4b0f00122c8ad8bcd4979dd755a001a7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/google/{{ name }}/archive/yapf-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - yapf = yapf:run_main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - yapf --help
    - yapf --version

about:
  home: https://github.com/google/yapf
  license: Apache 2.0
  summary: A formatter for Python files

extra:
  recipe-maintainers:
    - vamega
