{% set version = "0.11.0" %}

package:
  name: yapf
  version: {{ version }}

source:
  fn: yapf-{{ version }}.tar.gz
  url: https://github.com/google/yapf/archive/v{{ version }}.tar.gz
  md5: e6173b24083e905d041c817d9abcb949

build:
  entry_points:
    - yapf = yapf:run_main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - yapf --help
    - yapf --version

about:
  home: https://github.com/google/yapf
  license: Apache 2.0
  summary: A formatter for Python files

extra:
  recipe-maintainers:
    - vamega
