{% set name = "yapf" %}
{% set version = "0.13.1" %}
{% set sha256 = "ce6da59178dd1b49a588af8eb4f0b3f806908bb153164bbf275e760166a5621d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - yapf = yapf:run_main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - yapf --help
    - yapf --version

about:
  home: https://github.com/google/yapf
  license: Apache 2.0
  summary: A formatter for Python files

extra:
  recipe-maintainers:
    - vamega
