{% set name = "yapf" %}
{% set version = "0.13.2" %}
{% set sha256 = "508a14c46b8753945707ebc756af3b172e83e5d35c26d3648d3cab1c7408ae65" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - yapf = yapf:run_main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - yapf --help
    - yapf --version

about:
  home: https://github.com/google/yapf
  license: Apache 2.0
  summary: A formatter for Python files

extra:
  recipe-maintainers:
    - vamega
