travis:
  secure:
    BINSTAR_TOKEN: J4PFXLtdqH432XmeenBuOdcSPD2Ih3VPyDUQCA7L4pRPHkreYiITFpzs1L7PSkB6PhinZTvziN80f3Sh6DP6gC2WRgDaaGq0St82mUewjUAkjRJcGEC29LK22EEpqhz3FVBeIB/WaaP6xd66dHG7rn5u5aGf1MSwsKuVxapjl1ggZaJPyyKbnjtNQnAIKetydMF5dvnvS0Mz086mrLtAqfbpaVW4XqGUgF+YzY/TqlCPAqF451QaK3g+8FH1Ycu+lVB+TMJDBacIsoEhspss1Uv9YjSYjAy8ydust+s65oTnX6cwc4DBcKSXKYzUHbGNJh/9yY70OhAWP/fJ0Dl9j1B5DXTxUls2fBWRMawYOjoP9FqpO/08higYwSCrmlws7FSDm7xroViQnBr+B3lwl9a+78DXALLAdoI+ySVTeiSv+S8jDr2aXZWazmRzZ8fNnTKE2bNA/YQn5boCNgtbz2LHn90K5spkfox3eeX8iM0jSHvXaCry6w8PFvn+y33KuJ3FrcEGkuOedqC1LFFLC7KGW9Ia+bdfVoA02ZTp0FvpCNE/MiT2Lao4x0P+6zLnaqVPBSDUXG5RMX1Ro6SXJOTeh8jKwNWufc+jUZ3GCeidNUYVLpvqz+hJWRe15QEZ9Hlk39gLbafaGFTSRhJ8deS1riUhCXjhk3v9J1e/I+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
