travis:
  secure:
    BINSTAR_TOKEN: LUoKUeMlFkyggrQ0abOiwOooM7yDreWVAbsVO0bQlmpyd0fIaTORKFsR7egOcsRnFaB8JFQywVUZz9mweIqvaeCD8IDPQfZKdXTGoR+03tCy/j3VgXhwiRAR98SbmPwxY0Bkz9Mr/1kPV43Q87VvxIQBr6B9W8QDODc51D/0ywLNVLvU38L4tUu2mI89+wdA9MIHGrlN03N/lOyJ4gqwOeZTr53cq0E4wlPRJeX/PrhvNydK+vxTveIW6gisQ1ham7ghWget/9NiumzdXMId2if4vZJ9tWIYGA3Z2SQ7ba+E5zuChAsy0vYBRRH1XcN68+dv1pK7FX5xJEur1O2U4zH6lAyqG2MTelLzyqlkiPL+a8KWu90+dZibN19EoyHX9iw5tzBov1rkedxjL1odGXHjaMiu3wjjtaockdntykCrq4sAzmXtObb8gacfocFgJwtqqvEuskPEzq3U+WP6v0Gf2v2MBvWMookTohtyBBiEXNEuTNtlmiZOLmV55ebtzVyJFunnfqOpyUZzHGNGo+2ktWAvmGuK4+miz54+jrkHqtnT35CXCcJfsRPTVGS1gO0/gYsA0Y7q3yXsoKtFh9E7b1XQnIDkdooryLvEiRXainIwzYBr+UGN2E0AsX0AXUR2wSW2NIqey0OZw831YpMfm5AlO3FcR46s5BvQhqU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
