travis:
  secure:
    BINSTAR_TOKEN: lxmTxgFWGRFDddYwxh2J59wiXeDmPyxWPWGBkm5IoerZXPZ04l4Nw8MmcIBvUdDTeSv+9ZiIVevN/fmv7u1SuAw9o+MEsruBFl3X5hBTUCAUMZqZBiwdWG66osS3kd9aChpxF7iA7D2ewRCCkX0OMZd5yCjDQcAJl/joBF8JX/wIbLVOGiwYtXRgzI+mJL4UcymZUyG0RPYZ8X63PAE4JvWMQyg3cHAjh9eJj6QOChUwV6aEUnS8uoKMVx/HFIlcHKEquu8z3eRsK6RF5IAGmP5pxGwVUKQnVf4OQ3+mnJ6kVWQFG9yHiWvsuMS3pn82vOnpBouzE8oLec7FOWPuM+jbQDONf6xy+rwtvFad5qb7dtyZNb1yeEdfvHa2JcNOCo7rG1Et+WV15n5QNMPve4NIuDEINfFqJhnhrPrmRapdeThYInm0GdOdGHgCn90Uc0Ew1XOrFlSqSUIXZTxtUDJ4+GvCxKRD8tegZdYI9MVRgDQbzMmR3PHtOR8Zh1butxnDGjhtUWCkTK26MOVMicI/2V6dsmb7UItY9rQTwdCiDLx98AlHi3UODIH0MZKSOxiO04pfdTRG9pwqc7FmEnLTRnS9Y28IFJDEYn9uoij4vBbP4CX1RZVOWPUNPZuJ0cVVqmL9t9kWFJKwZOkIv4PGeZs48leVHlsjHCIUuy0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
